# Generated by Django 3.2.6 on 2025-03-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cc', models.CharField(max_length=10)),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
    ]
