# Generated by Django 4.2.20 on 2025-03-16 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoclinico',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='eventoclinico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eventos.paciente'),
        ),
    ]
